import PDFDocument from "pdfkit";

export default async function handler(req, res) {

  if (req.method !== "POST") {
    return res.status(405).end();
  }

  const {
    currency,
    currentRevenue,
    targetRevenue,
    incomeGap,
    materialCost,
    overhead,
    netProfit,
    profitMargin,
    breakEvenRevenue,
    projectsNeeded
  } = req.body;

  const doc = new PDFDocument({ margin: 0 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=Contractor-Profit-Report.pdf"
  );

  doc.pipe(res);

  const pageWidth = doc.page.width;

  /* =========================
     PAGE 1 – COVER
  ========================== */

  doc.rect(0, 0, pageWidth, 120).fill("#111111");

  doc.fillColor("white")
     .fontSize(26)
     .text("CONTRACTOR PROFIT REPORT", 0, 50, { align: "center" });

  doc.fillColor("#111111")
     .fontSize(16)
     .text("Executive Summary", 60, 180);

  doc.fontSize(13)
     .text(
       `Your business generates ${currency} ${currentRevenue.toLocaleString()} annually.`,
       60,
       220,
       { width: 480 }
     );

  doc.text(
       `Target revenue is ${currency} ${targetRevenue.toLocaleString()}, leaving a gap of ${currency} ${incomeGap.toLocaleString()}.`,
       { width: 480 }
     );

  // Income Gap Highlight
  doc.roundedRect(60, 320, 480, 90, 8).fill("#f4f4f4");

  doc.fillColor("#555")
     .fontSize(12)
     .text("INCOME GAP", 80, 340);

  doc.fillColor(incomeGap > 0 ? "#c0392b" : "#27ae60")
     .fontSize(26)
     .text(`${currency} ${incomeGap.toLocaleString()}`, 80, 360);

  doc.addPage();

  /* =========================
     PAGE 2 – DASHBOARD
  ========================== */

  doc.fillColor("#111111")
     .fontSize(22)
     .text("Financial Dashboard", 60, 60);

  const boxWidth = 160;
  const boxHeight = 80;
  const startX = 60;
  const startY = 110;
  const gap = 20;

  function kpiBox(x, y, title, value, color) {
    doc.roundedRect(x, y, boxWidth, boxHeight, 6).fill("#f7f7f7");
    doc.fillColor("#777")
       .fontSize(10)
       .text(title, x + 15, y + 15);
    doc.fillColor(color)
       .fontSize(16)
       .text(value, x + 15, y + 35);
  }

  const profitColor = netProfit >= 0 ? "#27ae60" : "#c0392b";
  const marginColor = profitMargin >= 20 ? "#27ae60" : "#c0392b";

  kpiBox(startX, startY, "Net Profit",
    `${currency} ${netProfit.toLocaleString()}`, profitColor);

  kpiBox(startX + boxWidth + gap, startY, "Profit Margin",
    `${profitMargin}%`, marginColor);

  kpiBox(startX + (boxWidth + gap) * 2, startY, "Break-even",
    `${currency} ${breakEvenRevenue.toLocaleString()}`, "#000000");

  /* ===== REVENUE ===== */

  doc.fillColor("#111111")
     .fontSize(16)
     .text("Revenue Performance", 60, 230);

  doc.moveTo(60, 250)
     .lineTo(pageWidth - 60, 250)
     .strokeColor("#dddddd")
     .stroke();

  doc.fontSize(12).fillColor("#000");

  doc.text("Current Revenue:", 60, 270)
     .fillColor("#27ae60")
     .text(`${currency} ${currentRevenue.toLocaleString()}`, 400, 270);

  doc.fillColor("#000")
     .text("Target Revenue:", 60, 290)
     .fillColor("#000")
     .text(`${currency} ${targetRevenue.toLocaleString()}`, 400, 290);

  /* ===== COST ===== */

  doc.fillColor("#111111")
     .fontSize(16)
     .text("Cost Structure", 60, 330);

  doc.moveTo(60, 350)
     .lineTo(pageWidth - 60, 350)
     .strokeColor("#dddddd")
     .stroke();

  doc.fontSize(12).fillColor("#000");

  doc.text("Material Cost:", 60, 370)
     .text(`${currency} ${materialCost.toLocaleString()}`, 400, 370);

  doc.text("Annual Overhead:", 60, 390)
     .text(`${currency} ${overhead.toLocaleString()}`, 400, 390);

  /* ===== OPERATIONS ===== */

  doc.fillColor("#111111")
     .fontSize(16)
     .text("Operational Requirement", 60, 430);

  doc.moveTo(60, 450)
     .lineTo(pageWidth - 60, 450)
     .strokeColor("#dddddd")
     .stroke();

  doc.fontSize(12).fillColor("#000");

  doc.text("Projects Needed to Reach Target:", 60, 470)
     .text(`${projectsNeeded}`, 400, 470);

  doc.fontSize(10)
     .fillColor("gray")
     .text("Generated by Contractor Profit AI",
       0,
       doc.page.height - 60,
       { align: "center" });

  doc.end();
}
