import chromium from "@sparticuz/chromium";
import puppeteer from "puppeteer-core";

export default async function handler(req, res) {

  if (req.method !== "POST") {
    return res.status(405).end();
  }

  try {

    const {
      currency = "USD",
      currentRevenue = 0,
      targetRevenue = 0,
      materialCost = 0,
      overhead = 0,
      netProfit = 0,
      profitMargin = 0,
      breakEvenRevenue = 0,
      projectsNeeded = 0
    } = req.body;

    const incomeGap = targetRevenue - currentRevenue;

    const gapPercent =
      targetRevenue > 0
        ? ((incomeGap / targetRevenue) * 100).toFixed(1)
        : 0;

    const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<style>

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  margin: 0;
  padding: 50px;
  background: #f8fafc;
  color: #0f172a;
}

h1 {
  font-size: 28px;
  margin-bottom: 10px;
}

h2 {
  font-size: 18px;
  margin-top: 40px;
  margin-bottom: 20px;
}

.header {
  border-bottom: 1px solid #e2e8f0;
  padding-bottom: 20px;
  margin-bottom: 30px;
}

.kpi-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 20px;
}

.card {
  background: white;
  padding: 20px;
  border-radius: 14px;
  box-shadow: 0 10px 25px rgba(0,0,0,0.05);
}

.label {
  font-size: 13px;
  color: #64748b;
}

.value {
  font-size: 22px;
  font-weight: 600;
  margin-top: 5px;
}

.green { color: #16a34a; }
.red { color: #dc2626; }

.bar-wrapper {
  margin-top: 15px;
}

.bar-bg {
  height: 12px;
  background: #e2e8f0;
  border-radius: 999px;
  overflow: hidden;
}

.bar-fill {
  height: 100%;
  border-radius: 999px;
}

.summary-box {
  background: white;
  padding: 25px;
  border-radius: 14px;
  box-shadow: 0 10px 25px rgba(0,0,0,0.05);
  margin-top: 30px;
}

ul {
  padding-left: 20px;
}

</style>
</head>

<body>

<div class="header">
  <h1>Contractor Profit Intelligence Report</h1>
  <div class="label">Generated by Contractor Profit AI</div>
</div>

<div class="kpi-grid">
  <div class="card">
    <div class="label">Current Revenue</div>
    <div class="value">${currency} ${Number(currentRevenue).toLocaleString()}</div>
  </div>

  <div class="card">
    <div class="label">Target Revenue</div>
    <div class="value">${currency} ${Number(targetRevenue).toLocaleString()}</div>
  </div>

  <div class="card">
    <div class="label">Income Gap</div>
    <div class="value ${incomeGap > 0 ? "red" : "green"}">
      ${currency} ${Number(incomeGap).toLocaleString()}
    </div>
  </div>

  <div class="card">
    <div class="label">Net Profit</div>
    <div class="value green">
      ${currency} ${Number(netProfit).toLocaleString()}
    </div>
  </div>

  <div class="card">
    <div class="label">Profit Margin</div>
    <div class="value">${profitMargin}%</div>
  </div>

  <div class="card">
    <div class="label">Projects Needed</div>
    <div class="value">${projectsNeeded}</div>
  </div>
</div>

<h2>Financial Performance</h2>

<div class="bar-wrapper">
  <div class="label">Revenue Progress</div>
  <div class="bar-bg">
    <div class="bar-fill" style="
      width:${Math.min((currentRevenue/targetRevenue)*100 || 0,100)}%;
      background:#16a34a;"></div>
  </div>
</div>

<div class="bar-wrapper">
  <div class="label">Cost Structure</div>
  <div class="bar-bg">
    <div class="bar-fill" style="
      width:${Math.min(((materialCost+overhead)/currentRevenue)*100 || 0,100)}%;
      background:#dc2626;"></div>
  </div>
</div>

<div class="bar-wrapper">
  <div class="label">Profit Strength</div>
  <div class="bar-bg">
    <div class="bar-fill" style="
      width:${profitMargin || 0}%;
      background:#0ea5e9;"></div>
  </div>
</div>

<div class="summary-box">
  <h2>Strategic Summary</h2>
  <p>
  Your business currently operates at a ${profitMargin}% margin.
  The revenue gap represents ${gapPercent}% of your target.
  Closing this gap will require structured pricing discipline,
  cost optimization, and improved project efficiency.
  </p>
</div>

<div class="summary-box">
  <h2>Action Plan</h2>
  <ul>
    <li>Increase pricing by 3–8% where market allows</li>
    <li>Negotiate supplier discounts and reduce material waste</li>
    <li>Improve quote-to-close conversion rate</li>
    <li>Track margin per project monthly</li>
  </ul>
</div>

</body>
</html>
`;

    const browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await browser.close();

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      "attachment; filename=\"Contractor-Profit-Report.pdf\""
    );

    res.status(200).send(pdfBuffer);

  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "PDF generation failed" });
  }
}
