import PDFDocument from "pdfkit";

export default async function handler(req, res) {

  if (req.method !== "POST") {
    return res.status(405).end();
  }

  const {
    currency,
    currentRevenue,
    targetRevenue,
    incomeGap,
    materialCost,
    overhead,
    netProfit,
    profitMargin,
    breakEvenRevenue,
    projectsNeeded
  } = req.body;

  const doc = new PDFDocument({ margin: 60 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    "attachment; filename=Contractor-Profit-Report.pdf"
  );

  doc.pipe(res);

  // ===== HEADER =====
  doc
    .fontSize(24)
    .fillColor("#000000")
    .text("CONTRACTOR PROFIT REPORT", { align: "center" });

  doc.moveDown(2);

  // ===== MAIN NUMBERS BLOCK =====
  doc
    .fontSize(18)
    .fillColor("#111111")
    .text("Revenue Overview");

  doc.moveDown(0.8);

  doc.fontSize(14);
  doc.text(`Current Revenue: ${currency} ${currentRevenue.toLocaleString()}`);
  doc.text(`Target Revenue: ${currency} ${targetRevenue.toLocaleString()}`);
  doc.text(`Income Gap: ${currency} ${incomeGap.toLocaleString()}`);

  doc.moveDown(1.5);

  // ===== COST STRUCTURE =====
  doc
    .fontSize(18)
    .fillColor("#111111")
    .text("Cost Structure");

  doc.moveDown(0.8);

  doc.fontSize(14);
  doc.text(`Material Cost: ${currency} ${materialCost.toLocaleString()}`);
  doc.text(`Annual Overhead: ${currency} ${overhead.toLocaleString()}`);

  doc.moveDown(1.5);

  // ===== PROFITABILITY =====
  doc
    .fontSize(18)
    .fillColor("#111111")
    .text("Profitability");

  doc.moveDown(0.8);

  doc.fontSize(14);
  doc.text(`Net Profit: ${currency} ${netProfit.toLocaleString()}`);
  doc.text(`Profit Margin: ${profitMargin}%`);
  doc.text(`Break-even Revenue: ${currency} ${breakEvenRevenue.toLocaleString()}`);

  doc.moveDown(1.5);

  // ===== OPERATIONS =====
  doc
    .fontSize(18)
    .fillColor("#111111")
    .text("Operational Metrics");

  doc.moveDown(0.8);

  doc.fontSize(14);
  doc.text(`Projects Needed to Hit Target: ${projectsNeeded}`);

  doc.moveDown(3);

  // ===== FOOTER =====
  doc
    .fontSize(10)
    .fillColor("gray")
    .text("Generated by Contractor Profit AI", {
      align: "center"
    });

  doc.end();
}
